LayerUtil is a simple resource decoder/encoder utiliy for Haven and Hearth

Requirements:
	JRE 7 or JDK 7

Compile with:
	ant clean jar
	
Run with:
    java -jar LayerUtil.jar [OPTION] [ARGS]
    
see `java -jar LayerUtil.jar -h' for more details 


Disclaimer:
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
	EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
	OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
	IN NO EVENT SHALL THE AUTHORS OR COPY RIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 	DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
	OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR 
	THE USE OR OTHER DEALINGS IN THE SOFTWARE.
